"""create initial tables

Revision ID: e211dc8d00a2
Revises: 
Create Date: 2026-09-18 19:27:14.366943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e211dc8d00a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_types_name'), 'object_types', ['name'], unique=True)
    op.create_table('astronomical_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('catalog_id', sa.String(length=100), nullable=True),
    sa.Column('object_type_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_id')
    )
    op.create_index(op.f('ix_astronomical_objects_name'), 'astronomical_objects', ['name'], unique=False)
    op.create_index(op.f('ix_astronomical_objects_object_type_id'), 'astronomical_objects', ['object_type_id'], unique=False)
    op.create_table('observation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('astronomical_object_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observatory', sa.Text(), nullable=True),
    sa.Column('magnitude', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('distance_au', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['astronomical_object_id'], ['astronomical_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observation_logs_astronomical_object_id'), 'observation_logs', ['astronomical_object_id'], unique=False)
    op.create_index(op.f('ix_observation_logs_observed_at'), 'observation_logs', ['observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observation_logs_observed_at'), table_name='observation_logs')
    op.drop_index(op.f('ix_observation_logs_astronomical_object_id'), table_name='observation_logs')
    op.drop_table('observation_logs')
    op.drop_index(op.f('ix_astronomical_objects_object_type_id'), table_name='astronomical_objects')
    op.drop_index(op.f('ix_astronomical_objects_name'), table_name='astronomical_objects')
    op.drop_table('astronomical_objects')
    op.drop_index(op.f('ix_object_types_name'), table_name='object_types')
    op.drop_table('object_types')
    # ### end Alembic commands ###
